version: '3'
services:
  know_the_curve_front:
    container_name: know_the_curve_front
    build: ./frontend
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HOST=0.0.0.0
    depends_on:
      - know_the_curve_back
    networks:
      - knowTheCurve
  know_the_curve_back:
    container_name: know_the_curve_back
    build: './backend'
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=secretpass
    depends_on:
      - db
    networks:
      - knowTheCurve
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpass
    networks:
      - knowTheCurve
  networks:
    - knowTheCurve
