# Generated by Django 2.1.15 on 2020-05-31 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('populacao', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('death_count', models.IntegerField()),
                ('cases_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('state_full_name', models.CharField(max_length=50)),
                ('ibge_locality_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='occurrence',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brazil.State'),
        ),
    ]
