# Generated by Django 2.1.15 on 2020-05-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brazil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='date',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='populacao',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='date_occured',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
